export enum ViewState {
    AUTH = 'AUTH',
    DASHBOARD = 'DASHBOARD',
    CHECK_IN = 'CHECK_IN',
    CHECK_OUT = 'CHECK_OUT'
}

export interface User {
    username: string;
    deviceId: string; // Browser-generated UUID to simulate MAC address binding
}

export interface WorkLog {
    id: string;
    username: string;
    jobName: string;
    checkInTime: string; // ISO String
    checkInLocation: {
        lat: number;
        lng: number;
    };
    checkOutTime?: string; // ISO String
    checkOutLocation?: {
        lat: number;
        lng: number;
    };
    status: 'CHECKED_IN' | 'CHECKED_OUT';
    aiSummary?: string; // Generated by Gemini
}

export interface GeoLocationState {
    coords: {
        latitude: number;
        longitude: number;
    } | null;
    error: string | null;
    loading: boolean;
}